// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cykwtravboemqqerznyj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5a3d0cmF2Ym9lbXFxZXJ6bnlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc3MzI1MjcsImV4cCI6MjA1MzMwODUyN30.JscMUzJ-r4s3a2PT3HwpvE447wnEsP6-wTx06MYSjpw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);